### ISSUE TITLE
Android App is not compiling

### ISSUE THREAD

**Issue by fjtrujy** [vgorloff/swift-everywhere-samples#13]
Hello,
I have been trying to make the android app to work, without no luck....

When I try to compile the error that I see is:
```sh
unknown option --triple; use --help to list available options
```

After some investigation looks like, it is using the `swift` installed globally in the computer (I'm using a Mac) instead of the one from the `swift-android-toolchain`

I have been investigating the `Build.rb` just to understand what you were doing, at the end looks like you execute something as:
```bash
/Users/fjtrujy/swift-everywhere-toolchain/ToolChain/swift-android-toolchain/usr/bin/android-swift-build --build-path "/Users/fjtrujy/Projects/swift-everywhere-samples//Android/app/build/swift-x86_64" -c release -target x86_64-unknown-linux-android -v
```
And then output is
```
export SWIFT_EXEC=/Users/fjtrujy/swift-everywhere-toolchain/ToolChain/swift-android-toolchain/usr/bin/swiftc-x86_64-linux-android
swift build --triple x86_64-unknown-linux-android --sdk /Users/fjtrujy/swift-everywhere-toolchain/ToolChain/swift-android-toolchain --toolchain /usr/local/ndk/20.1.5948944/toolchains/llvm/prebuilt/darwin-x86_64/bin -Xcc -I/usr/local/ndk/20.1.5948944/toolchains/llvm/prebuilt/darwin-x86_64/sysroot/usr/include -Xcc -I/usr/local/ndk/20.1.5948944/toolchains/llvm/prebuilt/darwin-x86_64/sysroot/usr/include/x86_64-linux-android --build-path /Users/fjtrujy/Projects/swift-everywhere-samples//Android/app/build/swift-x86_64 -c release -v
error: unknown option --triple; use --help to list available options
```

Exactly the same that the Android Studio returns.

Again, I think that somehow it is not using the proper swift executable and using the system one instead.

Thanks for your amazing work!

**Comment by vgorloff** [comment]
Hi,

What version of swift package manager you are using?
You can check it with command `swift build --version`.

Example output:

```bash
$ swift build --version
Swift Package Manager - Swift 5.3.0
```

**Comment by vgorloff** [comment]
The `--tripple` option was added this year at 25. February 2020 (SHA 19d1a137f99b1e35dfa3f94153a74923cdd30528)
https://github.com/apple/swift-package-manager/commit/19d1a137f99b1e35dfa3f94153a74923cdd30528#diff-8d396837a0426c26967e471b82d8f2eaf31f9a7ae2e03308300799edbac4bd18R382

Looks you are using old version of Xcode ;)

**Comment by fjtrujy** [comment]
Hello!
Thanks you are totally right! I forgot it but I executed this in order to be able to compile binutils/gcc (days ago) and I forgot to put it back
```bash
sudo xcode-select --switch /Applications/Xcode_11.7.app
```

Thanks changing it back to Xcode 12 worked fine.
